# AUTO-GENERATED by terraform/bootstrap. Do not edit by hand.
resource_group_name  = "rg-terraform"
storage_account_name  = "sttfstate4922m7vk"
container_name       = "terraformstate"
key                  = "prod.terraform.tfstate"
