# ============================================================================
# Terraform remote-state BOOTSTRAP
# ----------------------------------------------------------------------------
# Creates the Azure resources that hold Terraform remote state for every
# environment, and generates the per-environment backend.hcl files so
# `terraform init -backend-config=backend.hcl` in environments/<env> just works.
#
# Run ONCE per subscription, before any environment:
#   az login ; az account set --subscription <SUB_ID>
#   cd terraform/bootstrap
#   terraform init
#   terraform apply
#
# Uses local state (see versions.tf for why). Safe to re-run (idempotent).
# ============================================================================

# Random suffix so the storage account name is globally unique without manual
# guessing. Kept in local bootstrap state so it is stable across re-runs.
resource "random_string" "suffix" {
  length  = 8
  lower   = true
  upper   = false
  numeric = true
  special = false
}

resource "azurerm_resource_group" "state" {
  name     = var.state_resource_group_name
  location = var.location
  tags     = var.tags
}

resource "azurerm_storage_account" "state" {
  name                     = "sttfstate${random_string.suffix.result}"
  resource_group_name      = azurerm_resource_group.state.name
  location                 = azurerm_resource_group.state.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"

  # Blob versioning: protects state history against accidental corruption.
  blob_properties {
    versioning_enabled = true
  }

  tags = var.tags
}

resource "azurerm_storage_container" "state" {
  name                  = var.state_container_name
  storage_account_id    = azurerm_storage_account.state.id
  container_access_type = "private"
}

# Generate a backend.hcl for each environment so `terraform init
# -backend-config=backend.hcl` in environments/<env> uses this state account
# with a per-environment key. No manual copy/paste of the unique name.
resource "local_file" "backend_hcl" {
  for_each = toset(var.environments)

  filename = "${path.module}/../environments/${each.value}/backend.hcl"
  content  = <<-HCL
    # AUTO-GENERATED by terraform/bootstrap. Do not edit by hand.
    resource_group_name  = "${azurerm_resource_group.state.name}"
    storage_account_name  = "${azurerm_storage_account.state.name}"
    container_name       = "${azurerm_storage_container.state.name}"
    key                  = "${each.value}.terraform.tfstate"
  HCL
}
